version: "3"
services:
  sqlserver:
	image: "mcr.microsoft.com/mssql/server:2019-latest"
	container_name: "sqlserver"
	environment:
		ACCEPT_EULA: "Y"
		SA_PASSWORD: "password"
		MSSQL_PID: "Express"
	ports:
		-"1433:1433"
